import { access, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { PreviewFile, PreviewPack } from "./schemas.js";

export type InitMode = "dry_run" | "write";

export type InitResult = {
  mode: InitMode;
  repoPath: string;
  files: Array<{
    sourcePath: string;
    targetPath: string;
    purpose: string;
    status: "preview" | "written";
  }>;
};

export async function runInit(preview: PreviewPack, options: { write?: boolean }): Promise<InitResult> {
  const mode: InitMode = options.write ? "write" : "dry_run";
  const files = preview.files.map((file) => ({
    sourcePath: file.path,
    targetPath: targetPathForPreview(file),
    purpose: file.purpose,
    status: mode === "write" ? ("written" as const) : ("preview" as const),
  }));

  if (mode === "write") {
    for (const file of preview.files) {
      const relativePath = targetPathForPreview(file);
      const absolutePath = path.join(preview.repoPath, relativePath);

      await mkdir(path.dirname(absolutePath), { recursive: true });
      await assertDoesNotExist(absolutePath);
      await writeFile(absolutePath, withGeneratedHeader(file.content), "utf8");
    }
  }

  return {
    mode,
    repoPath: preview.repoPath,
    files,
  };
}

export function renderInitResult(result: InitResult, preview: PreviewPack): string {
  const header =
    result.mode === "write"
      ? "# Lumo Init\n\nFiles written. Existing files are never overwritten."
      : "# Lumo Init Preview\n\nNo files were written. Use `--write` only after reviewing the proposed files.";

  return [
    header,
    "",
    `Repo: ${result.repoPath}`,
    `Mode: ${result.mode}`,
    "",
    "| File | Status | Purpose |",
    "| --- | --- | --- |",
    ...result.files.map((file) => `| ${file.targetPath} | ${file.status} | ${file.purpose} |`),
    "",
    ...(result.mode === "dry_run" ? renderPreviewContents(preview) : []),
    result.mode === "dry_run"
      ? "Next: run `init --write` only if these files match the repo."
      : "Next: review the written files, edit them to fit the repo, and commit only what you understand.",
    "",
  ].join("\n");
}

function renderPreviewContents(preview: PreviewPack): string[] {
  return preview.files.flatMap((file) => [
    `## ${targetPathForPreview(file)}`,
    "",
    `Purpose: ${file.purpose}`,
    "",
    ["```md", withGeneratedHeader(file.content).trim(), "```"].join("\n"),
    "",
  ]);
}

function targetPathForPreview(file: PreviewFile): string {
  if (file.path === "AGENTS.md.draft") return "AGENTS.md";
  if (file.path === "CLAUDE.md.draft") return "CLAUDE.md";
  return file.path;
}

async function assertDoesNotExist(absolutePath: string): Promise<void> {
  try {
    await access(absolutePath);
  } catch {
    return;
  }

  throw new Error(`Refusing to overwrite existing file: ${absolutePath}`);
}

function withGeneratedHeader(content: string): string {
  return [
    "<!-- Generated by Lumo Harness. Safe to edit manually. -->",
    "<!-- Review before committing. Regenerate instead of blindly overwriting user edits. -->",
    "",
    content.trim(),
    "",
  ].join("\n");
}
